"""empty message

Revision ID: 4940f921f160
Revises: 8da77067778
Create Date: 2016-07-11 10:58:43.809728

"""

# revision identifiers, used by Alembic.
revision = '4940f921f160'
down_revision = '8da77067778'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_tag_ref',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], )
    )
    op.add_column(u'posts', sa.Column('title', sa.String(length=128), nullable=True))
    op.create_index('ix_posts_title', 'posts', ['title'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_posts_title', 'posts')
    op.drop_column(u'posts', 'title')
    op.drop_table('post_tag_ref')
    ### end Alembic commands ###
